#! /bin/sh

pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5

bspc config border_width          1
bspc config normal_border_color   "$color1"
bspc config focused_border_color  "$color2"
bspc config window_gap            20
bspc config top_padding           20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a st-256color state=floating
bspc rule -a Min desktop=^2

# Polybar
# sh $HOME/.config/polybar/launch.sh &
sudo pkill lemonbar
sudo pkill lemonbar
sudo pkill lemonbar
pkill lemonbar
pkill lemonbar
pkill lemonbar

bash $HOME/.config/lemonbar/bar

# xsetroot
xsetroot -cursor_name left_ptr &
# hsetroot -fill $HOME/dotfiles/wallpapers/output.jpg
