#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc -a st -o floating=true

xsetroot -cursor_name left_ptr &

# Picom
picom --animations --animation-for-open-window zoom &
# Polybar
$HOME/.config/polybar/launch.sh
