#!/bin/sh

Workspace() {
  # Agrega aquí la lógica para obtener y mostrar los nombres de los espacios de trabajo
  workspaces=("st" "min" "mpv" "virt")
  current_ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
  output=""
  for ((i=0; i<${#workspaces[@]}; i++)); do
      if [ $i -eq $current_ws ]; then
          output+="%{B#a6949e}%{F#FFFFFF} ${workspaces[i]} %{B-}%{F-}"
      else
          output+=" ${workspaces[i]} "
      fi
  done
  echo -e "$output"
}

Hora() {
  h=$(date +'%I:%M %p')
  echo $h
}

Wifi() {
  if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    echo "Connected"
  else
    echo "Disconnected"
  fi
}

Batery() {
  BATERY=$(cat /sys/class/power_supply/BATT/capacity)
  STATUS=$(cat /sys/class/power_supply/BATT/status)
  echo "$BATERY% $STATUS"
}

Title() {
  len=$(echo -n "$(xdotool getwindowfocus getwindowname)" | wc -m)
  max_len=70
  if [ "$len" -gt "$max_len" ];then
    echo -n "$(xdotool getwindowfocus getwindowname | cut -c 1-$max_len)..."
  else
    echo -n "$(xdotool getwindowfocus getwindowname)"
  fi
}

while true; do
  echo "%{l}$(Workspace) %{c} $(Title) %{r} $(Batery) | $(Wifi) | $(Hora)"
  sleep 0.1
done | lemonbar -p -d -f "JetBrainsMono Nerd Font:size=8" -B "#111111" &
