#!/bin/sh -e

SEP="|"

b="%{B-}"
Green="%{B#667651}"
Red="%{B#91615e}"
Yellow="%{B#a18a5d}"
Orange="%{B#997459}"
Aqua="%{B#7f8d8a}"

Date() {
  h=$(date +'%A, %d.%m.%Y %I:%M %P')
  echo "$h"
}

Volume() {
    state=$(amixer get Master | awk '$0~/%/{print $6}' | tr -d '[]')
    v=$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]')
    
    if [ "$state" = "off" ]; then
        echo -n "$Yellow Muted $b"
    else
        echo -n "$Yellow $v $b"
    fi
}

Memory() {
	m=$(free -m | awk '/Mem:/ {printf "%d", $3}')
	echo -n "$Green $m $b"
}

Cpu() {
	c=$(top -bn1 | grep "Cpu(s)" | \
						sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
						awk '{print 100 - $1"%"}')
	echo -n "$Red $c $b"
}

Name() {
    window_name=$(xdotool getwindowfocus getwindowname)
    if [ ${#window_name} -gt 20 ]; then
        # Truncar a 30 caracteres y agregar '...'
        printf '%.20s...\n' "$window_name"
    else
        # Mostrar el nombre completo si tiene menos de 30 caracteres
        printf '%s\n' "$window_name"
    fi
}

Cap() {
	cap=$(xset q | awk '/Caps Lock/ {print $4}')
	echo -n "$Aqua $cap $b"
}

User() {
	echo -n "$Orange $(hostname) $b" 
}

Workspaces() {
    desktops=$(bspc query -D --names)
    current=$(bspc query -D -d focused --names)

    output=""

    for desktop in $desktops; do
        if [ "$desktop" = "$current" ]; then
            output="$output %{F#7f8d8a}[$desktop]%{F-} "
        else
            output="$output $desktop "
        fi
    done

    echo "$output"
}

Center() {
	x=$(xdotool getdisplaygeometry | awk '{print $1}')
	c=$(($x - 800))
	echo $c
}

Left() {
	x=$(xdotool getdisplaygeometry | awk '{print $1}')
	center=$(($x - 1100))
	a=$(($center / 2))
	echo $a
}

while true; do
	echo "%{l}$(User) $(Workspaces) $(Name) %{c}$(Date)%{r} Cpu $(Cpu) Mem $(Memory) Vol $(Volume) Cap $(Cap)"
	sleep 0.1s
done | lemonbar -B "#081d21" -f "MartianMono Nerd Font:style:Regular:size=7" -g $(Center)x20+$(Left)+10 &
