#!/bin/sh -e

SEP="|"

b="%{B-}"
Green="%{B#667651}"
Red="%{B#91615e}"
Yellow="%{B#a18a5d}"
Orange="%{B#997459}"
Aqua="%{B#7f8d8a}"

Date() {
  h=$(date +'%A, %d.%m.%Y %I:%M %P')
  echo "$h"
}

Volume() {
    state=$(amixer get Master | awk '$0~/%/{print $6}' | tr -d '[]')
    v=$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]')
    
    if [ "$state" = "off" ]; then
        echo -n "$Yellow Muted $b"
    else
        echo -n "$Yellow $v $b"
    fi
}

Memory() {
	m=$(free -m | awk '/Mem:/ {printf "%d", $3}')
	echo -n "$Green $m $b"
}

Cpu() {
	c=$(top -bn1 | grep "Cpu(s)" | \
						sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
						awk '{print 100 - $1"%"}')
	echo -n "$Red $c $b"
}

Name() {
		printf '%s' "$(xdotool getwindowfocus getwindowname | awk '{print substr($0, 1, 30)}')"
}

Cap() {
	cap=$(xset q | awk '/Caps Lock/ {print $4}')
	echo -n "$Aqua $cap $b"
}

User() {
	echo -n "$Orange $(hostname) $b" 
}

Center() {
	x=$(xdotool getdisplaygeometry | awk '{print $1}')
	c=$(($x - 1000))
	echo $c
}

Left() {
	x=$(xdotool getdisplaygeometry | awk '{print $1}')
	center=$(($x - 1000))
	a=$(($center / 2))
	echo $a
}

while true; do
	echo "%{l}$(User) $(Name) %{c}$(Date)%{r} Cpu $(Cpu) Mem $(Memory) Vol $(Volume) Cap $(Cap)"
	sleep 0.1s
done | lemonbar -B "#081D21" -f "MartianMono Nerd Font:style:Regular:size=7" -g $(Center)x20+$(Left)+10 &
