# Shell variables
# Generated by 'wal'
wallpaper='/home/alyssa/wallpapers/emma2.jpg'

# Special
background='#0C020C'
foreground='#f2e1af'
cursor='#f2e1af'

# Colors
color0='#0C020C'
color1='#635650'
color2='#875A26'
color3='#8E6A2D'
color4='#A97430'
color5='#B9723C'
color6='#C19341'
color7='#f2e1af'
color8='#a99d7a'
color9='#635650'
color10='#875A26'
color11='#8E6A2D'
color12='#A97430'
color13='#B9723C'
color14='#C19341'
color15='#f2e1af'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
