# Shell variables
# Generated by 'wal'
wallpaper='/home/alyssa/wallpapers/wal30.jpg'

# Special
background='#0C020C'
foreground='#afbcb6'
cursor='#afbcb6'

# Colors
color0='#0f1512'
color1='#5E563B'
color2='#2B3D42'
color3='#35534B'
color4='#505147'
color5='#646559'
color6='#88756C'
color7='#afbcb6'
color8='#7a837f'
color9='#5E563B'
color10='#2B3D42'
color11='#35534B'
color12='#505147'
color13='#646559'
color14='#88756C'
color15='#afbcb6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
