[colors]

[colors.primary]
	# background = "#09171a"
	background = "#071013"
	#foreground = "#f8e7c2"
	foreground = "#d5d4d7"	

	[colors.normal]
		black    = "#1b2b30" # sin cambios
		red      = "#915a5a" # sin cambios
		green    = "#5c7a53" # sin cambios
		yellow   = "#a18a5d" # sin cambios
		blue     = "#3a6f94" # ajustado para mayor contraste
		magenta  = "#8b4b59" # ajustado para mayor contraste
		cyan     = "#2f8887" # ajustado para mayor contraste
		white    = "#f4ebd7"

  [colors.bright]
		black    = "#959496" # sin cambios
		red      = "#915a5a" # sin cambios
		green    = "#5c7a53" # sin cambios
		yellow   = "#a18a5d" # sin cambios
		blue     = "#3a6f94" # ajustado para mayor contraste
		magenta  = "#8b4b59" # ajustado para mayor contraste
		cyan     = "#2f8887" # ajustado para mayor contraste
		white    = "#f4ebd7" # sin cambios
