[colors.primary]
  background = "#09171a"  # Mantengo el fondo oscuro
  foreground = "#f8e7c2"  # Foreground claro, como mencionaste

[colors.normal]
  black = "#1b2b30"       # Mantengo el negro oscuro
  red = "#b85757"         # Aumento la saturación del rojo para más viveza
  green = "#6a9150"       # Un verde más saturado y distinto al cyan
  yellow = "#b19b63"      # Hago el amarillo más brillante para más contraste
  blue = "#4b6b84"        # Un azul más saturado y oscuro, distinto del cyan
  magenta = "#b0785d"     # Hago el magenta más rosado y distinto del red
  cyan = "#5ca4a4"        # Hago el cyan más vibrante para que resalte del azul
  white = "#f4ebd7"       # Mantengo el blanco claro pero suave

[colors.bright]
  black = "#2a3c43"       # Hago el negro brillante un poco más claro
  red = "#b85757"         # Aumento la saturación del rojo para más viveza
  green = "#6a9150"       # Un verde más saturado y distinto al cyan
  yellow = "#b19b63"      # Hago el amarillo más brillante para más contraste
  blue = "#4b6b84"        # Un azul más saturado y oscuro, distinto del cyan
  magenta = "#b0785d"     # Hago el magenta más rosado y distinto del red
  cyan = "#5ca4a4"        # Hago el cyan más vibrante para que resalte del azul
  white = "#f4ebd7"       # Mantengo el blanco claro pero suave
