[colors]

  [colors.primary]
  background = "#09171a"
  foreground = "#e2dcc9"

  [colors.normal]
  black = "#1b2b30"
  red = "#a65b5b"
  green = "#6f8561"
  yellow = "#c9b281"
  blue = "#4b657f"
  magenta = "#b28574"
  cyan = "#6b8a8a"
  white = "#f8e7c2"

  [colors.bright]
  black = "#1b2b30"
  red = "#a65b5b"
  green = "#6f8561"
  yellow = "#c9b281"
  blue = "#4b657f"
  magenta = "#b28574"
  cyan = "#6b8a8a"
  white = "#f8e7c2"
