# Colors (Solarized Osaka)
# Source https://github.com/craftzdog/solarized-osaka.nvim

# Default colors
[colors.primary]
background = '#001a1d'
# background = '#0f1b1a'
# background = '#151f22'
# background = '#101516'
# background = '#002B36'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'
