[colors]
[colors.primary]
background = "#141b1e"
foreground = "#dadada"

[colors.normal]
black = '#191b1c'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7aa6da'
magenta = '#e78a4e'
cyan = '#89b482'
white = '#b3b9b8'

[colors.bright]
black = '#2a3437'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7aa6da'
magenta = '#e78a4e'
cyan = '#89b482'
white = '#b3b9b8'
