[colors]
[colors.primary]
# background = "#101214"
# background = '#181b23'
# background = '#0c100c'
# background = '#0d1416'
# foreground = "#dadada"
# background = '#191b1c'
background = '#131516'
# background = '#111213'
# background = '#1b1d1e'
# foreground = '#ECE7D5'
# foreground = '#d7c9ae'
# foreground = '#eae0d2'
foreground = '#ebdbb2'

[colors.normal]
black = '#191b1c'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7aa6da'
magenta = '#e78a4e'
cyan = '#89b482'
white = '#d7c9ae'

[colors.bright]
black = '#2a3437'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7aa6da'
magenta = '#e78a4e'
cyan = '#89b482'
white = '#d7c9ae'
